// <auto-generated />
using System;
using LMS.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LMS.API.Migrations
{
    [DbContext(typeof(LMSDbContext))]
    partial class LMSDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("LMS.API.Entities.Alumno", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.Property<int>("GradoId")
                        .HasColumnType("int")
                        .HasColumnName("grado_id");

                    b.HasKey("UsuarioId");

                    b.HasIndex("GradoId")
                        .HasDatabaseName("idx_alumnos_grado");

                    b.ToTable("alumnos", (string)null);
                });

            modelBuilder.Entity("LMS.API.Entities.ArchivoEntrega", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EntregaId")
                        .HasColumnType("int")
                        .HasColumnName("entrega_id");

                    b.Property<DateTime>("FechaSubida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_subida")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nombre_archivo");

                    b.Property<string>("NombreOriginal")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nombre_original");

                    b.Property<string>("RutaArchivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("ruta_archivo");

                    b.Property<ulong>("TamanoBytes")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("tamano_bytes");

                    b.Property<string>("TipoMime")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("tipo_mime");

                    b.HasKey("Id");

                    b.HasIndex("EntregaId")
                        .HasDatabaseName("idx_archivos_entrega");

                    b.ToTable("archivos_entrega", (string)null);
                });

            modelBuilder.Entity("LMS.API.Entities.Curso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<int>("DocenteId")
                        .HasColumnType("int")
                        .HasColumnName("docente_id");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("GradoId")
                        .HasColumnType("int")
                        .HasColumnName("grado_id");

                    b.Property<string>("Grupo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("grupo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("DocenteId")
                        .HasDatabaseName("idx_cursos_docente");

                    b.HasIndex("GradoId")
                        .HasDatabaseName("idx_cursos_grado");

                    b.HasIndex("Nombre", "GradoId", "Grupo")
                        .IsUnique()
                        .HasDatabaseName("uq_cursos_nombre_grado_grupo");

                    b.ToTable("cursos", (string)null);
                });

            modelBuilder.Entity("LMS.API.Entities.Entrega", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlumnoId")
                        .HasColumnType("int")
                        .HasColumnName("alumno_id");

                    b.Property<decimal?>("Calificacion")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("calificacion");

                    b.Property<string>("ContenidoTexto")
                        .HasColumnType("text")
                        .HasColumnName("contenido_texto");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("ENVIADA")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaCalificacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_calificacion");

                    b.Property<DateTime>("FechaEntrega")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_entrega")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Retroalimentacion")
                        .HasColumnType("text")
                        .HasColumnName("retroalimentacion");

                    b.Property<int>("TareaId")
                        .HasColumnType("int")
                        .HasColumnName("tarea_id");

                    b.HasKey("Id");

                    b.HasIndex("AlumnoId")
                        .HasDatabaseName("idx_entregas_alumno");

                    b.HasIndex("TareaId")
                        .HasDatabaseName("idx_entregas_tarea");

                    b.HasIndex("TareaId", "AlumnoId")
                        .IsUnique()
                        .HasDatabaseName("uq_entrega_tarea_alumno");

                    b.ToTable("entregas", (string)null);
                });

            modelBuilder.Entity("LMS.API.Entities.Grado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("uq_grados_nombre");

                    b.ToTable("grados", (string)null);
                });

            modelBuilder.Entity("LMS.API.Entities.Inscripcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlumnoId")
                        .HasColumnType("int")
                        .HasColumnName("alumno_id");

                    b.Property<int>("CursoId")
                        .HasColumnType("int")
                        .HasColumnName("curso_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("ACTIVA")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_registro")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("AlumnoId")
                        .HasDatabaseName("idx_inscripciones_alumno");

                    b.HasIndex("CursoId")
                        .HasDatabaseName("idx_inscripciones_curso");

                    b.HasIndex("CursoId", "AlumnoId")
                        .IsUnique()
                        .HasDatabaseName("uq_inscripcion_curso_alumno");

                    b.ToTable("inscripciones", (string)null);
                });

            modelBuilder.Entity("LMS.API.Entities.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<int>("CursoId")
                        .HasColumnType("int")
                        .HasColumnName("curso_id");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<DateTime>("FechaPublicacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_publicacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("RecursoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("recurso_url");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("tipo");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("titulo");

                    b.HasKey("Id");

                    b.HasIndex("CursoId")
                        .HasDatabaseName("idx_materiales_curso");

                    b.ToTable("materiales", (string)null);
                });

            modelBuilder.Entity("LMS.API.Entities.Perfil", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("apellido");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("avatar_url");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("UsuarioId");

                    b.ToTable("perfiles", (string)null);
                });

            modelBuilder.Entity("LMS.API.Entities.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("uq_roles_nombre");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("LMS.API.Entities.Tarea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<int>("CursoId")
                        .HasColumnType("int")
                        .HasColumnName("curso_id");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<DateTime>("FechaLimite")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_limite");

                    b.Property<DateTime>("FechaPublicacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_publicacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal>("PuntajeMaximo")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(100.00m)
                        .HasColumnName("puntaje_maximo");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("titulo");

                    b.HasKey("Id");

                    b.HasIndex("CursoId")
                        .HasDatabaseName("idx_tareas_curso");

                    b.ToTable("tareas", (string)null);
                });

            modelBuilder.Entity("LMS.API.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<int>("RolId")
                        .HasColumnType("int")
                        .HasColumnName("rol_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("RolId")
                        .HasDatabaseName("idx_usuarios_rol");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("uq_usuarios_username");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("LMS.API.Entities.Alumno", b =>
                {
                    b.HasOne("LMS.API.Entities.Grado", "Grado")
                        .WithMany("Alumnos")
                        .HasForeignKey("GradoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_alumnos_grados");

                    b.HasOne("LMS.API.Entities.Usuario", "Usuario")
                        .WithOne("Alumno")
                        .HasForeignKey("LMS.API.Entities.Alumno", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_alumnos_usuarios");

                    b.Navigation("Grado");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("LMS.API.Entities.ArchivoEntrega", b =>
                {
                    b.HasOne("LMS.API.Entities.Entrega", "Entrega")
                        .WithMany("Archivos")
                        .HasForeignKey("EntregaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_archivos_entrega");

                    b.Navigation("Entrega");
                });

            modelBuilder.Entity("LMS.API.Entities.Curso", b =>
                {
                    b.HasOne("LMS.API.Entities.Usuario", "Docente")
                        .WithMany("CursosDocente")
                        .HasForeignKey("DocenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cursos_docentes");

                    b.HasOne("LMS.API.Entities.Grado", "Grado")
                        .WithMany("Cursos")
                        .HasForeignKey("GradoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cursos_grados");

                    b.Navigation("Docente");

                    b.Navigation("Grado");
                });

            modelBuilder.Entity("LMS.API.Entities.Entrega", b =>
                {
                    b.HasOne("LMS.API.Entities.Alumno", "Alumno")
                        .WithMany("Entregas")
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_entregas_alumnos");

                    b.HasOne("LMS.API.Entities.Tarea", "Tarea")
                        .WithMany("Entregas")
                        .HasForeignKey("TareaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_entregas_tareas");

                    b.Navigation("Alumno");

                    b.Navigation("Tarea");
                });

            modelBuilder.Entity("LMS.API.Entities.Inscripcion", b =>
                {
                    b.HasOne("LMS.API.Entities.Alumno", "Alumno")
                        .WithMany("Inscripciones")
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inscripciones_alumnos");

                    b.HasOne("LMS.API.Entities.Curso", "Curso")
                        .WithMany("Inscripciones")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inscripciones_cursos");

                    b.Navigation("Alumno");

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("LMS.API.Entities.Material", b =>
                {
                    b.HasOne("LMS.API.Entities.Curso", "Curso")
                        .WithMany("Materiales")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_materiales_cursos");

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("LMS.API.Entities.Perfil", b =>
                {
                    b.HasOne("LMS.API.Entities.Usuario", "Usuario")
                        .WithOne("Perfil")
                        .HasForeignKey("LMS.API.Entities.Perfil", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_perfiles_usuarios");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("LMS.API.Entities.Tarea", b =>
                {
                    b.HasOne("LMS.API.Entities.Curso", "Curso")
                        .WithMany("Tareas")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tareas_cursos");

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("LMS.API.Entities.Usuario", b =>
                {
                    b.HasOne("LMS.API.Entities.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_usuarios_roles");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("LMS.API.Entities.Alumno", b =>
                {
                    b.Navigation("Entregas");

                    b.Navigation("Inscripciones");
                });

            modelBuilder.Entity("LMS.API.Entities.Curso", b =>
                {
                    b.Navigation("Inscripciones");

                    b.Navigation("Materiales");

                    b.Navigation("Tareas");
                });

            modelBuilder.Entity("LMS.API.Entities.Entrega", b =>
                {
                    b.Navigation("Archivos");
                });

            modelBuilder.Entity("LMS.API.Entities.Grado", b =>
                {
                    b.Navigation("Alumnos");

                    b.Navigation("Cursos");
                });

            modelBuilder.Entity("LMS.API.Entities.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("LMS.API.Entities.Tarea", b =>
                {
                    b.Navigation("Entregas");
                });

            modelBuilder.Entity("LMS.API.Entities.Usuario", b =>
                {
                    b.Navigation("Alumno");

                    b.Navigation("CursosDocente");

                    b.Navigation("Perfil");
                });
#pragma warning restore 612, 618
        }
    }
}
